# Generated by Django 3.2.5 on 2021-08-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='dete_added',
            new_name='date_added',
        ),
    ]
